### ISSUE TITLE
Thread of additions + updates

### ISSUE THREAD

**Issue by louisfh** [rhine3/bioacoustics-software#4]
Name: Deepsqueak

A Matlab package

https://github.com/DrCoffey/DeepSqueak 

Open Source

**Comment by NickleDave** [comment]
Another project that also uses neural networks for object detection to identify calls:
https://www.dietrich-lab.org/vocalmat

Same goal but segments audio with an algorithm instead of treating it as a computer vision task:
https://github.com/rtachi-lab/usvseg

Can test the Google form with these :slightly_smiling_face:

**Comment by NickleDave** [comment]
And this that just came out today :stuck_out_tongue: 
https://asa.scitation.org/doi/full/10.1121/10.0012350
https://github.com/DiogoMPessoa/Mice-USVs-segmentation-and-classification

**Comment by NickleDave** [comment]
Oh right, and one more
https://github.com/mvansegbroeck/mupet

**Comment by NickleDave** [comment]
And https://github.com/shainetser/TrackUSF

**Comment by rhine3** [comment]
Add Wildtrax - https://www.wildtrax.ca/home

**Comment by rhine3** [comment]
Suggestions from Michael Pitzrick at CLO:

The BirdNET link in your list is deprecated. The current URL is [github.com/kahst/BirdNET-Analyzer](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkahst%2FBirdNET-Analyzer&data=05%7C01%7Ctessa.rhinehart%40pitt.edu%7Cb67c2798e390471eedc408da7e6be125%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637961299058939876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wuLNHOGTyThwQgmeIQ%2FdPo7XzF1GACFS4OJ%2BTwX4434%3D&reserved=0). Note that BirdNET Analyzer is now available as a Windows application with GUI support, so may be more accessible to non-programmers than before.

[MANTA](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbitbucket.org%2FCLO-BRP%2Fmanta-wiki%2Fwiki%2FHome&data=05%7C01%7Ctessa.rhinehart%40pitt.edu%7Cb67c2798e390471eedc408da7e6be125%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637961299058939876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0a%2FjyAD%2BlIPvhmc0YnJFpl3944Zks3wb97H9TKNEgMI%3D&reserved=0) enables valid comparison between soundscapes and identification of ambient ocean sound trends required by ocean stakeholders.

eBird now recommends Ocenaudio and WavePad (in addition to Audition and Audacity) for sound editing, so perhaps these would be worthy of your list. See [Audio preparation and upload guidelines](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.ebird.org%2Fen%2Fsupport%2Fsolutions%2Farticles%2F48001064341-audio-preparation-and-upload-guidelines&data=05%7C01%7Ctessa.rhinehart%40pitt.edu%7Cb67c2798e390471eedc408da7e6be125%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637961299058939876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QcTx%2B6KkcAW4AUpZAYROKUE0oBgi%2BlucB9Jmz3ReY34%3D&reserved=0).

[Sox-o-matic](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.birds.cornell.edu%2Fccb%2Fsox-o-matic%2F&data=05%7C01%7Ctessa.rhinehart%40pitt.edu%7Cb67c2798e390471eedc408da7e6be125%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637961299058939876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3kbxiWlksfyoYRdkUf%2Fw1o3TS4tlumhcfiLSRQybgwI%3D&reserved=0) is utility software designed to compress audio, convert audio format, and rename audio files in batches.

**Comment by rhine3** [comment]
Add das: https://github.com/janclemenslab/das
* CNN segmenter for lab vocalizations
* Nice annotation interface

**Comment by rhine3** [comment]
Add soundClass -- bioacoustic CNN training in R

https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13964?af=R

**Comment by rhine3** [comment]
Add CASE 

https://www.mdpi.com/2076-2615/12/16/2020

**Comment by rhine3** [comment]
Add ANIMAL-SPOT https://www.nature.com/articles/s41598-022-26429-y

**Comment by rhine3** [comment]
Working through these updates--giving them a 👍  once I've added them or a 👎 if I have reviewed them and decided not to include them.

For example:
> And https://github.com/shainetser/TrackUSF

I think I'm not going to add this, because it's not recent or under active development (most recent update was 2 years ago).

**Comment by rhine3** [comment]
All updates above been made to the spreadsheet. We will integrate these updates into a website in #3; the README will no probably longer contain the list.
