### ISSUE TITLE
Thread of additions and updates: 2023

### ISSUE THREAD

**Issue by rhine3** [rhine3/bioacoustics-software#8]
Add the following:
* [x] Pykanto: https://arxiv.org/pdf/2302.10340v1.pdf
* [x] Nighthawk: https://github.com/bmvandoren/Nighthawk/
* [x] pypam: https://github.com/lifewatch/pypam for long-term underwater acoustics data visualization, focused on ML for bioacoustics
* [x] pyporcc: https://github.com/lifewatch/pyporcc a python version of the PAMGuard click detector, together with a published click classifier
* [x] a collection of jupyter notebooks to categorize soundscapes in an unsupervised way: https://github.com/lifewatch/categorizing_soundscapes/tree/main
* [x]  https://github.com/earthspecies/aves (and maybe other packages from ESP? https://github.com/earthspecies)
* [x] https://github.com/earthspecies/cocktail-party-problem
* [x] https://git-dev.cs.dal.ca/meridian/NARW_detection_tool
* [x] https://bitbucket.org/CLO-BRP/manta-wiki/wiki/Home
* [x] https://github.com/schonkopf/soundscape_IR
* [x] https://ecosound-web.de/ecosound_web/
* [x] Detector and Classifier https://github.com/htleblond/PAMGuardMIRRF
* [x] Revision tool for hourly detection SoundScope: https://github.com/xaviermouy/SoundScope
* [x] Tethys: https://tethys.sdsu.edu/ detections and metadata management, also good for exploring detections
* [x] DAS data processing https://github.com/leabouffaut/DAS4Whales
* [x] Some guidelines for people starting with python: https://github.com/leabouffaut/bioacoustics_python
* [x] ENSTA-Bretagne annotation tool: https://github.com/Project-OSmOSE/osmose-app/tree/1.8.3
* [x] https://github.com/david-rx/BioLingual
* [x] General: add a column in the excel sheet which indicates ecosystem the software is suitable for (Marine/Terrestrial/Both)

==> To be moved to another issue: Switch the main homepage to be the list and make columns collapsible e.g. style of - https://bioacoustic-ai.github.io/bioacoustics-datasets/

**Comment by cparcerisas** [comment]
Software shown/presented/cited at DLCDE2024 workshop: 

- Detector and Classifier   https://github.com/htleblond/PAMGuardMIRRF  
- Revision tool for hourly detection SoundScope: https://github.com/xaviermouy/SoundScope 
- Tethys: https://tethys.sdsu.edu/  detections and metadata management, also good for exploring detections 
- DAS data processing https://github.com/leabouffaut/DAS4Whales 
- Some guidelines for people starting with python: https://github.com/leabouffaut/bioacoustics_python 
- ENSTA-Bretagne annotation tool: https://github.com/Project-OSmOSE/osmose-app/tree/1.8.3
 
Other software:

  - https://github.com/david-rx/BioLingual

And another question, do you think it would be possible to add a column in the excel sheet which indicates if it is suitable for Marine/Terrestrial/Both Bioacoustics? 

Thank you for the work of maintaining this, it is very useful!!

Best, 
Clea

**Comment by cparcerisas** [comment]
Other software: 
- https://github.com/david-rx/BioLingual

**Comment by cparcerisas** [comment]
Should I submit a form for each of these? https://docs.google.com/forms/d/e/1FAIpQLSdE_UX-bvohtBLSXTAKbtapvR5wuw30WWIZcCjROp4HsdklTQ/viewform

**Comment by rhine3** [comment]
@cparcerisas THANK YOU so much for submitting these! Replying to this thread is the best way to share updates with me right now, no need to also submit the form.

You wouldn't happen to be interested in helping me maintain this repository, would you? 

Also - I'd be happy to add a column for marine/terrestrial suitability. I will add it to the to-do list :)

**Comment by cparcerisas** [comment]
Hey @rhine3, sure, I'd be happy to help out! 
Just that I am very busy until end of June and then I take two months off, but if you can use my help from September on I'd be happy to contribute in maintaining it! It is very helpful for me and my colleagues :)

**Comment by cparcerisas** [comment]
Hey @rhine3, I'm back available to help update this. I see that there is a publication in preparation using your database: https://zenodo.org/records/12096525, would be good that the list is updated if possible :)
What do you think?

**Comment by rhine3** [comment]
Hi @cparcerisas! Thank you so much for offering to help.

Since you last wrote, my lab decided to update this list ourselves, so we are working on a complete refresh of the list to include it in a paper we're writing. 

The software you've provided above is already really helpful - if you could let me know about any other updates/additions you think are important as they come up, that would be great.

**Comment by cparcerisas** [comment]
Hi @rhine3 this is great! Thanks for the updates. I just saw this paper in preparation: https://zenodo.org/records/12096525
And they are citing the database, but without the updates. Do you have a timeline for when will the list be updated? I would like to inform them, as most of the newly developed tools for underwater (bio)acoustics are very relevant :)
And I will keep reporting whenever I hear of other tools :)

**Comment by rhine3** [comment]
Hi Clea, I really appreciate you offering to reach out to them. While I'm hoping to be done with a full refresh of the sheet by mid-October, I just did a quick add of the changes you suggested and created a DOI/citation for the spreadsheet - [10.5281/zenodo.7686203](https://doi.org/10.5281/zenodo.7686203). Could you please convey that to these folks?

**Comment by cparcerisas** [comment]
Amazing thank you so much! However I only see added the ones I proposed in my last comment, but not the ones proposed in 2023 (which were added by you to the list to add, in the thread) 

pypam: https://github.com/lifewatch/pypam for long-term underwater acoustics data visualization, focused on ML for bioacoustics
pyporcc: https://github.com/lifewatch/pyporcc a python version of the PAMGuard click detector, together with a published click classifier
https://github.com/earthspecies/aves
https://github.com/earthspecies/cocktail-party-problem
https://git-dev.cs.dal.ca/meridian/NARW_detection_tool
https://bitbucket.org/CLO-BRP/manta-wiki/wiki/Home
https://github.com/schonkopf/soundscape_IR
https://ecosound-web.de/ecosound_web/
Detector and Classifier https://github.com/htleblond/PAMGuardMIRRF
Revision tool for hourly detection SoundScope: https://github.com/xaviermouy/SoundScope
Tethys: https://tethys.sdsu.edu/ detections and metadata management, also good for exploring detections
DAS data processing https://github.com/leabouffaut/DAS4Whales
Some guidelines for people starting with python: https://github.com/leabouffaut/bioacoustics_python
ENSTA-Bretagne annotation tool: https://github.com/Project-OSmOSE/osmose-app/tree/1.8.3

Sorry for that, but would it be possible to add these ones for the citation? Thank you again so much for the work!!

**Comment by rhine3** [comment]
Ah good point, we'll work on adding those in the next couple of days, too :)

One of my colleagues is helping me update the list, so the updated citation will include her name as well.

**Comment by cparcerisas** [comment]
Amazing, thank you!!!

**Comment by rhine3** [comment]
Hey again Clea! We have finished making our updates. Note that they won't be reflected on the website - I'm having trouble getting the website to build, so we're planning on moving it to a new format. Thus, the DOI release only contains an .xlsx version of the Google Spreadsheet.

Here is our citation!
> Rhinehart, T. A., Nicholson, D., Freeland-Haynes, L., Nossan, H., Sochat, V., & Kitzes, J. (2024). Bioacoustics Software Database (v0.3). Zenodo. https://doi.org/10.5281/zenodo.13800100

**Comment by rhine3** [comment]
All updates made to the website, closed by #13
