### ISSUE TITLE
Other software

### ISSUE THREAD

**Issue by cparcerisas** [rhine3/bioacoustics-software#9]
Thanks for the work done! Very useful compilation. 

Do you think our packages (under development) would meet the criteria to be on this list? 
pypam: https://github.com/lifewatch/pypam for long-term underwater acoustics data visualization, focused on ML for bioacoustics 
pyporcc: https://github.com/lifewatch/pyporcc a python version of the PAMGuard click detector, together with a published click classifier 

We also published a collection of jupyter notebooks to categorize soundscapes in an unsupervised way:
https://github.com/lifewatch/categorizing_soundscapes/tree/main 

Furthermore, not ours but maybe also interesting: 
https://github.com/earthspecies/aves (and maybe other packages from ESP? https://github.com/earthspecies) 
https://github.com/earthspecies/cocktail-party-problem
https://git-dev.cs.dal.ca/meridian/NARW_detection_tool
https://bitbucket.org/CLO-BRP/manta-wiki/wiki/Home
https://github.com/schonkopf/soundscape_IR
https://github.com/kitzeslab/opensoundscape

Thank you!

**Comment by rhine3** [comment]
Hi Clea, yes, packages or resources that are actively in development but are already in a usable state definitely qualify for the software list.  Thanks so much for sharing all of these resources. This list is really helpful and I will be sure to add these items in the next update!

I have added all of these to my thread of additions and updates to make on the next revision of the repository, #8 (with the exception of OpenSoundscape, which is my lab's package--it's definitely already on the list!)
